// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAom1_5w9iAFRWjYWpmFa3sGntuTPX0S9o',
    appId: '1:647763543576:web:246c1614e5283841d1656d',
    messagingSenderId: '647763543576',
    projectId: 'testershare-dfcda',
    authDomain: 'testershare-dfcda.firebaseapp.com',
    storageBucket: 'testershare-dfcda.appspot.com',
    measurementId: 'G-4SFNSL4S95',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAczroEmMdl79IhHm89Bo8jJWmE4P8Hfzw',
    appId: '1:647763543576:android:6ecabb776f52f51ad1656d',
    messagingSenderId: '647763543576',
    projectId: 'testershare-dfcda',
    storageBucket: 'testershare-dfcda.appspot.com',
  );
}
